# Build & Deploy Hugo to GitHub Pages (Project Pages)
name: Build & Deploy Hugo site to Pages

on:
  push:
    branches: [ main ]   # jalankan tiap push ke main
  workflow_dispatch:      # bisa dijalankan manual dari tab Actions

# Wajib untuk deploy via actions/deploy-pages
permissions:
  contents: read
  pages: write
  id-token: write

# Hindari deploy tumpang tindih
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true         # kalau theme via submodule/Hugo Modules
          fetch-depth: 0

      # Go dibutuhkan untuk Hugo Modules. Pakai channel stable biar aman.
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.148.2'
          extended: true

      # Penting: configure-pages memberi output base_url yang sesuai (otomatis /awesome-blog)
      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Build
        run: |
          # optional: rapihin module cache
          hugo mod tidy || true
          # override baseURL agar selalu sesuai URL Pages project (tanpa hardcode)
          hugo --minify --baseURL "${{ steps.pages.outputs.base_url }}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
